name: Releases

on: 
  push:
    branches:
      - criteo
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [5.4.1]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
